// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: temporal/api/cloud/account/v1/message.proto

package account

import (
	v1 "go.temporal.io/cloud-sdk/api/resource/v1"
	v11 "go.temporal.io/cloud-sdk/api/sink/v1"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditLogSink_Health int32

const (
	AuditLogSink_HEALTH_UNSPECIFIED              AuditLogSink_Health = 0
	AuditLogSink_HEALTH_OK                       AuditLogSink_Health = 1
	AuditLogSink_HEALTH_ERROR_INTERNAL           AuditLogSink_Health = 2
	AuditLogSink_HEALTH_ERROR_USER_CONFIGURATION AuditLogSink_Health = 3
)

// Enum value maps for AuditLogSink_Health.
var (
	AuditLogSink_Health_name = map[int32]string{
		0: "HEALTH_UNSPECIFIED",
		1: "HEALTH_OK",
		2: "HEALTH_ERROR_INTERNAL",
		3: "HEALTH_ERROR_USER_CONFIGURATION",
	}
	AuditLogSink_Health_value = map[string]int32{
		"HEALTH_UNSPECIFIED":              0,
		"HEALTH_OK":                       1,
		"HEALTH_ERROR_INTERNAL":           2,
		"HEALTH_ERROR_USER_CONFIGURATION": 3,
	}
)

func (x AuditLogSink_Health) Enum() *AuditLogSink_Health {
	p := new(AuditLogSink_Health)
	*p = x
	return p
}

func (x AuditLogSink_Health) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AuditLogSink_Health) Descriptor() protoreflect.EnumDescriptor {
	return file_temporal_api_cloud_account_v1_message_proto_enumTypes[0].Descriptor()
}

func (AuditLogSink_Health) Type() protoreflect.EnumType {
	return &file_temporal_api_cloud_account_v1_message_proto_enumTypes[0]
}

func (x AuditLogSink_Health) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AuditLogSink_Health.Descriptor instead.
func (AuditLogSink_Health) EnumDescriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{5, 0}
}

type MetricsSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The ca cert(s) in PEM format that clients connecting to the metrics endpoint can use for authentication.
	// This must only be one value, but the CA can have a chain.
	AcceptedClientCa []byte `protobuf:"bytes,2,opt,name=accepted_client_ca,json=acceptedClientCa,proto3" json:"accepted_client_ca,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *MetricsSpec) Reset() {
	*x = MetricsSpec{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetricsSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetricsSpec) ProtoMessage() {}

func (x *MetricsSpec) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetricsSpec.ProtoReflect.Descriptor instead.
func (*MetricsSpec) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *MetricsSpec) GetAcceptedClientCa() []byte {
	if x != nil {
		return x.AcceptedClientCa
	}
	return nil
}

type AccountSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The metrics specification for this account.
	// If not specified, metrics will not be enabled.
	Metrics       *MetricsSpec `protobuf:"bytes,1,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AccountSpec) Reset() {
	*x = AccountSpec{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AccountSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AccountSpec) ProtoMessage() {}

func (x *AccountSpec) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AccountSpec.ProtoReflect.Descriptor instead.
func (*AccountSpec) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *AccountSpec) GetMetrics() *MetricsSpec {
	if x != nil {
		return x.Metrics
	}
	return nil
}

type Metrics struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The prometheus metrics endpoint uri.
	// This is only populated when the metrics is enabled in the metrics specification.
	Uri           string `protobuf:"bytes,1,opt,name=uri,proto3" json:"uri,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Metrics) Reset() {
	*x = Metrics{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Metrics) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Metrics) ProtoMessage() {}

func (x *Metrics) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Metrics.ProtoReflect.Descriptor instead.
func (*Metrics) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{2}
}

func (x *Metrics) GetUri() string {
	if x != nil {
		return x.Uri
	}
	return ""
}

type Account struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The id of the account.
	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	// The account specification.
	Spec *AccountSpec `protobuf:"bytes,2,opt,name=spec,proto3" json:"spec,omitempty"`
	// The current version of the account specification.
	// The next update operation will have to include this version.
	ResourceVersion string `protobuf:"bytes,3,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// The current state of the account.
	State v1.ResourceState `protobuf:"varint,4,opt,name=state,proto3,enum=temporal.api.cloud.resource.v1.ResourceState" json:"state,omitempty"`
	// The id of the async operation that is updating the account, if any.
	AsyncOperationId string `protobuf:"bytes,5,opt,name=async_operation_id,json=asyncOperationId,proto3" json:"async_operation_id,omitempty"`
	// Information related to metrics.
	Metrics       *Metrics `protobuf:"bytes,6,opt,name=metrics,proto3" json:"metrics,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Account) Reset() {
	*x = Account{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Account) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Account) ProtoMessage() {}

func (x *Account) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Account.ProtoReflect.Descriptor instead.
func (*Account) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{3}
}

func (x *Account) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Account) GetSpec() *AccountSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Account) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *Account) GetState() v1.ResourceState {
	if x != nil {
		return x.State
	}
	return v1.ResourceState(0)
}

func (x *Account) GetAsyncOperationId() string {
	if x != nil {
		return x.AsyncOperationId
	}
	return ""
}

func (x *Account) GetMetrics() *Metrics {
	if x != nil {
		return x.Metrics
	}
	return nil
}

// AuditLogSinkSpec is only used by Audit Log
type AuditLogSinkSpec struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the sink e.g. "audit_log_01"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Types that are valid to be assigned to SinkType:
	//
	//	*AuditLogSinkSpec_KinesisSink
	//	*AuditLogSinkSpec_PubSubSink
	SinkType isAuditLogSinkSpec_SinkType `protobuf_oneof:"sink_type"`
	// Enabled indicates whether the sink is enabled or not.
	Enabled       bool `protobuf:"varint,4,opt,name=enabled,proto3" json:"enabled,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AuditLogSinkSpec) Reset() {
	*x = AuditLogSinkSpec{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogSinkSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogSinkSpec) ProtoMessage() {}

func (x *AuditLogSinkSpec) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogSinkSpec.ProtoReflect.Descriptor instead.
func (*AuditLogSinkSpec) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{4}
}

func (x *AuditLogSinkSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuditLogSinkSpec) GetSinkType() isAuditLogSinkSpec_SinkType {
	if x != nil {
		return x.SinkType
	}
	return nil
}

func (x *AuditLogSinkSpec) GetKinesisSink() *v11.KinesisSpec {
	if x != nil {
		if x, ok := x.SinkType.(*AuditLogSinkSpec_KinesisSink); ok {
			return x.KinesisSink
		}
	}
	return nil
}

func (x *AuditLogSinkSpec) GetPubSubSink() *v11.PubSubSpec {
	if x != nil {
		if x, ok := x.SinkType.(*AuditLogSinkSpec_PubSubSink); ok {
			return x.PubSubSink
		}
	}
	return nil
}

func (x *AuditLogSinkSpec) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

type isAuditLogSinkSpec_SinkType interface {
	isAuditLogSinkSpec_SinkType()
}

type AuditLogSinkSpec_KinesisSink struct {
	// The KinesisSpec when destination_type is Kinesis
	KinesisSink *v11.KinesisSpec `protobuf:"bytes,2,opt,name=kinesis_sink,json=kinesisSink,proto3,oneof"`
}

type AuditLogSinkSpec_PubSubSink struct {
	// The PubSubSpec when destination_type is PubSub
	PubSubSink *v11.PubSubSpec `protobuf:"bytes,3,opt,name=pub_sub_sink,json=pubSubSink,proto3,oneof"`
}

func (*AuditLogSinkSpec_KinesisSink) isAuditLogSinkSpec_SinkType() {}

func (*AuditLogSinkSpec_PubSubSink) isAuditLogSinkSpec_SinkType() {}

// AuditLogSink is only used by Audit Log
type AuditLogSink struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Name of the sink e.g. "audit_log_01"
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// The version of the audit log sink resource.
	ResourceVersion string `protobuf:"bytes,2,opt,name=resource_version,json=resourceVersion,proto3" json:"resource_version,omitempty"`
	// The current state of the audit log sink.
	State v1.ResourceState `protobuf:"varint,3,opt,name=state,proto3,enum=temporal.api.cloud.resource.v1.ResourceState" json:"state,omitempty"`
	// The specification details of the audit log sink.
	Spec *AuditLogSinkSpec `protobuf:"bytes,4,opt,name=spec,proto3" json:"spec,omitempty"`
	// The health status of the audit log sink.
	Health AuditLogSink_Health `protobuf:"varint,5,opt,name=health,proto3,enum=temporal.api.cloud.account.v1.AuditLogSink_Health" json:"health,omitempty"`
	// An error message describing any issues with the audit log sink, if applicable.
	ErrorMessage string `protobuf:"bytes,6,opt,name=error_message,json=errorMessage,proto3" json:"error_message,omitempty"`
	// The last succeeded timestamp for the internal workflow responsible for adding data to the sink.
	LastSucceededTime *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=last_succeeded_time,json=lastSucceededTime,proto3" json:"last_succeeded_time,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *AuditLogSink) Reset() {
	*x = AuditLogSink{}
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditLogSink) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditLogSink) ProtoMessage() {}

func (x *AuditLogSink) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_account_v1_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditLogSink.ProtoReflect.Descriptor instead.
func (*AuditLogSink) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP(), []int{5}
}

func (x *AuditLogSink) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *AuditLogSink) GetResourceVersion() string {
	if x != nil {
		return x.ResourceVersion
	}
	return ""
}

func (x *AuditLogSink) GetState() v1.ResourceState {
	if x != nil {
		return x.State
	}
	return v1.ResourceState(0)
}

func (x *AuditLogSink) GetSpec() *AuditLogSinkSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AuditLogSink) GetHealth() AuditLogSink_Health {
	if x != nil {
		return x.Health
	}
	return AuditLogSink_HEALTH_UNSPECIFIED
}

func (x *AuditLogSink) GetErrorMessage() string {
	if x != nil {
		return x.ErrorMessage
	}
	return ""
}

func (x *AuditLogSink) GetLastSucceededTime() *timestamppb.Timestamp {
	if x != nil {
		return x.LastSucceededTime
	}
	return nil
}

var File_temporal_api_cloud_account_v1_message_proto protoreflect.FileDescriptor

const file_temporal_api_cloud_account_v1_message_proto_rawDesc = "" +
	"\n" +
	"+temporal/api/cloud/account/v1/message.proto\x12\x1dtemporal.api.cloud.account.v1\x1a,temporal/api/cloud/resource/v1/message.proto\x1a(temporal/api/cloud/sink/v1/message.proto\x1a\x1fgoogle/protobuf/timestamp.proto\";\n" +
	"\vMetricsSpec\x12,\n" +
	"\x12accepted_client_ca\x18\x02 \x01(\fR\x10acceptedClientCa\"S\n" +
	"\vAccountSpec\x12D\n" +
	"\ametrics\x18\x01 \x01(\v2*.temporal.api.cloud.account.v1.MetricsSpecR\ametrics\"\x1b\n" +
	"\aMetrics\x12\x10\n" +
	"\x03uri\x18\x01 \x01(\tR\x03uri\"\xb9\x02\n" +
	"\aAccount\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12>\n" +
	"\x04spec\x18\x02 \x01(\v2*.temporal.api.cloud.account.v1.AccountSpecR\x04spec\x12)\n" +
	"\x10resource_version\x18\x03 \x01(\tR\x0fresourceVersion\x12C\n" +
	"\x05state\x18\x04 \x01(\x0e2-.temporal.api.cloud.resource.v1.ResourceStateR\x05state\x12,\n" +
	"\x12async_operation_id\x18\x05 \x01(\tR\x10asyncOperationId\x12@\n" +
	"\ametrics\x18\x06 \x01(\v2&.temporal.api.cloud.account.v1.MetricsR\ametrics\"\xe7\x01\n" +
	"\x10AuditLogSinkSpec\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12L\n" +
	"\fkinesis_sink\x18\x02 \x01(\v2'.temporal.api.cloud.sink.v1.KinesisSpecH\x00R\vkinesisSink\x12J\n" +
	"\fpub_sub_sink\x18\x03 \x01(\v2&.temporal.api.cloud.sink.v1.PubSubSpecH\x00R\n" +
	"pubSubSink\x12\x18\n" +
	"\aenabled\x18\x04 \x01(\bR\aenabledB\v\n" +
	"\tsink_type\"\x85\x04\n" +
	"\fAuditLogSink\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12)\n" +
	"\x10resource_version\x18\x02 \x01(\tR\x0fresourceVersion\x12C\n" +
	"\x05state\x18\x03 \x01(\x0e2-.temporal.api.cloud.resource.v1.ResourceStateR\x05state\x12C\n" +
	"\x04spec\x18\x04 \x01(\v2/.temporal.api.cloud.account.v1.AuditLogSinkSpecR\x04spec\x12J\n" +
	"\x06health\x18\x05 \x01(\x0e22.temporal.api.cloud.account.v1.AuditLogSink.HealthR\x06health\x12#\n" +
	"\rerror_message\x18\x06 \x01(\tR\ferrorMessage\x12J\n" +
	"\x13last_succeeded_time\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\x11lastSucceededTime\"o\n" +
	"\x06Health\x12\x16\n" +
	"\x12HEALTH_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tHEALTH_OK\x10\x01\x12\x19\n" +
	"\x15HEALTH_ERROR_INTERNAL\x10\x02\x12#\n" +
	"\x1fHEALTH_ERROR_USER_CONFIGURATION\x10\x03B\xa7\x01\n" +
	" io.temporal.api.cloud.account.v1B\fMessageProtoP\x01Z+go.temporal.io/api/cloud/account/v1;account\xaa\x02\x1fTemporalio.Api.Cloud.Account.V1\xea\x02#Temporalio::Api::Cloud::Account::V1b\x06proto3"

var (
	file_temporal_api_cloud_account_v1_message_proto_rawDescOnce sync.Once
	file_temporal_api_cloud_account_v1_message_proto_rawDescData []byte
)

func file_temporal_api_cloud_account_v1_message_proto_rawDescGZIP() []byte {
	file_temporal_api_cloud_account_v1_message_proto_rawDescOnce.Do(func() {
		file_temporal_api_cloud_account_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_cloud_account_v1_message_proto_rawDesc), len(file_temporal_api_cloud_account_v1_message_proto_rawDesc)))
	})
	return file_temporal_api_cloud_account_v1_message_proto_rawDescData
}

var file_temporal_api_cloud_account_v1_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_temporal_api_cloud_account_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_temporal_api_cloud_account_v1_message_proto_goTypes = []any{
	(AuditLogSink_Health)(0),      // 0: temporal.api.cloud.account.v1.AuditLogSink.Health
	(*MetricsSpec)(nil),           // 1: temporal.api.cloud.account.v1.MetricsSpec
	(*AccountSpec)(nil),           // 2: temporal.api.cloud.account.v1.AccountSpec
	(*Metrics)(nil),               // 3: temporal.api.cloud.account.v1.Metrics
	(*Account)(nil),               // 4: temporal.api.cloud.account.v1.Account
	(*AuditLogSinkSpec)(nil),      // 5: temporal.api.cloud.account.v1.AuditLogSinkSpec
	(*AuditLogSink)(nil),          // 6: temporal.api.cloud.account.v1.AuditLogSink
	(v1.ResourceState)(0),         // 7: temporal.api.cloud.resource.v1.ResourceState
	(*v11.KinesisSpec)(nil),       // 8: temporal.api.cloud.sink.v1.KinesisSpec
	(*v11.PubSubSpec)(nil),        // 9: temporal.api.cloud.sink.v1.PubSubSpec
	(*timestamppb.Timestamp)(nil), // 10: google.protobuf.Timestamp
}
var file_temporal_api_cloud_account_v1_message_proto_depIdxs = []int32{
	1,  // 0: temporal.api.cloud.account.v1.AccountSpec.metrics:type_name -> temporal.api.cloud.account.v1.MetricsSpec
	2,  // 1: temporal.api.cloud.account.v1.Account.spec:type_name -> temporal.api.cloud.account.v1.AccountSpec
	7,  // 2: temporal.api.cloud.account.v1.Account.state:type_name -> temporal.api.cloud.resource.v1.ResourceState
	3,  // 3: temporal.api.cloud.account.v1.Account.metrics:type_name -> temporal.api.cloud.account.v1.Metrics
	8,  // 4: temporal.api.cloud.account.v1.AuditLogSinkSpec.kinesis_sink:type_name -> temporal.api.cloud.sink.v1.KinesisSpec
	9,  // 5: temporal.api.cloud.account.v1.AuditLogSinkSpec.pub_sub_sink:type_name -> temporal.api.cloud.sink.v1.PubSubSpec
	7,  // 6: temporal.api.cloud.account.v1.AuditLogSink.state:type_name -> temporal.api.cloud.resource.v1.ResourceState
	5,  // 7: temporal.api.cloud.account.v1.AuditLogSink.spec:type_name -> temporal.api.cloud.account.v1.AuditLogSinkSpec
	0,  // 8: temporal.api.cloud.account.v1.AuditLogSink.health:type_name -> temporal.api.cloud.account.v1.AuditLogSink.Health
	10, // 9: temporal.api.cloud.account.v1.AuditLogSink.last_succeeded_time:type_name -> google.protobuf.Timestamp
	10, // [10:10] is the sub-list for method output_type
	10, // [10:10] is the sub-list for method input_type
	10, // [10:10] is the sub-list for extension type_name
	10, // [10:10] is the sub-list for extension extendee
	0,  // [0:10] is the sub-list for field type_name
}

func init() { file_temporal_api_cloud_account_v1_message_proto_init() }
func file_temporal_api_cloud_account_v1_message_proto_init() {
	if File_temporal_api_cloud_account_v1_message_proto != nil {
		return
	}
	file_temporal_api_cloud_account_v1_message_proto_msgTypes[4].OneofWrappers = []any{
		(*AuditLogSinkSpec_KinesisSink)(nil),
		(*AuditLogSinkSpec_PubSubSink)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_cloud_account_v1_message_proto_rawDesc), len(file_temporal_api_cloud_account_v1_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_cloud_account_v1_message_proto_goTypes,
		DependencyIndexes: file_temporal_api_cloud_account_v1_message_proto_depIdxs,
		EnumInfos:         file_temporal_api_cloud_account_v1_message_proto_enumTypes,
		MessageInfos:      file_temporal_api_cloud_account_v1_message_proto_msgTypes,
	}.Build()
	File_temporal_api_cloud_account_v1_message_proto = out.File
	file_temporal_api_cloud_account_v1_message_proto_goTypes = nil
	file_temporal_api_cloud_account_v1_message_proto_depIdxs = nil
}
