// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        (unknown)
// source: temporal/api/cloud/auditlog/v1/message.proto

package auditlog

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// LogRecord represents an audit log entry from Temporal, structured for easy parsing and analysis.
type LogRecord struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Time when the log was emitted.
	EmitTime *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=emit_time,json=emitTime,proto3" json:"emit_time,omitempty"`
	// The operation performed.
	Operation string `protobuf:"bytes,5,opt,name=operation,proto3" json:"operation,omitempty"`
	// The status of the operation.
	Status string `protobuf:"bytes,7,opt,name=status,proto3" json:"status,omitempty"`
	// The internal version of the log message.  Can be used in deduplication if needed.
	Version int32 `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	// Unique ID for the log record.
	LogId string `protobuf:"bytes,10,opt,name=log_id,json=logId,proto3" json:"log_id,omitempty"`
	// The principal that performed the operation.
	Principal *Principal `protobuf:"bytes,12,opt,name=principal,proto3" json:"principal,omitempty"`
	// The raw details of the operation.
	RawDetails *structpb.Struct `protobuf:"bytes,13,opt,name=raw_details,json=rawDetails,proto3" json:"raw_details,omitempty"`
	// The originating IP address of the request.
	XForwardedFor string `protobuf:"bytes,14,opt,name=x_forwarded_for,json=xForwardedFor,proto3" json:"x_forwarded_for,omitempty"`
	// The ID of the async operation.
	AsyncOperationId string `protobuf:"bytes,15,opt,name=async_operation_id,json=asyncOperationId,proto3" json:"async_operation_id,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *LogRecord) Reset() {
	*x = LogRecord{}
	mi := &file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogRecord) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogRecord) ProtoMessage() {}

func (x *LogRecord) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogRecord.ProtoReflect.Descriptor instead.
func (*LogRecord) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_auditlog_v1_message_proto_rawDescGZIP(), []int{0}
}

func (x *LogRecord) GetEmitTime() *timestamppb.Timestamp {
	if x != nil {
		return x.EmitTime
	}
	return nil
}

func (x *LogRecord) GetOperation() string {
	if x != nil {
		return x.Operation
	}
	return ""
}

func (x *LogRecord) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *LogRecord) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *LogRecord) GetLogId() string {
	if x != nil {
		return x.LogId
	}
	return ""
}

func (x *LogRecord) GetPrincipal() *Principal {
	if x != nil {
		return x.Principal
	}
	return nil
}

func (x *LogRecord) GetRawDetails() *structpb.Struct {
	if x != nil {
		return x.RawDetails
	}
	return nil
}

func (x *LogRecord) GetXForwardedFor() string {
	if x != nil {
		return x.XForwardedFor
	}
	return ""
}

func (x *LogRecord) GetAsyncOperationId() string {
	if x != nil {
		return x.AsyncOperationId
	}
	return ""
}

type Principal struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The type of the principal.
	// Possible type values: user, serviceaccount.
	Type string `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	// The id of the principal.
	Id string `protobuf:"bytes,2,opt,name=id,proto3" json:"id,omitempty"`
	// The name of the principal.
	Name string `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	// The api key id of the principal if provided.
	ApiKeyId      string `protobuf:"bytes,4,opt,name=api_key_id,json=apiKeyId,proto3" json:"api_key_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Principal) Reset() {
	*x = Principal{}
	mi := &file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Principal) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Principal) ProtoMessage() {}

func (x *Principal) ProtoReflect() protoreflect.Message {
	mi := &file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Principal.ProtoReflect.Descriptor instead.
func (*Principal) Descriptor() ([]byte, []int) {
	return file_temporal_api_cloud_auditlog_v1_message_proto_rawDescGZIP(), []int{1}
}

func (x *Principal) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *Principal) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Principal) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Principal) GetApiKeyId() string {
	if x != nil {
		return x.ApiKeyId
	}
	return ""
}

var File_temporal_api_cloud_auditlog_v1_message_proto protoreflect.FileDescriptor

const file_temporal_api_cloud_auditlog_v1_message_proto_rawDesc = "" +
	"\n" +
	",temporal/api/cloud/auditlog/v1/message.proto\x12\x1etemporal.api.cloud.auditlog.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x84\x03\n" +
	"\tLogRecord\x127\n" +
	"\temit_time\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\bemitTime\x12\x1c\n" +
	"\toperation\x18\x05 \x01(\tR\toperation\x12\x16\n" +
	"\x06status\x18\a \x01(\tR\x06status\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x12\x15\n" +
	"\x06log_id\x18\n" +
	" \x01(\tR\x05logId\x12G\n" +
	"\tprincipal\x18\f \x01(\v2).temporal.api.cloud.auditlog.v1.PrincipalR\tprincipal\x128\n" +
	"\vraw_details\x18\r \x01(\v2\x17.google.protobuf.StructR\n" +
	"rawDetails\x12&\n" +
	"\x0fx_forwarded_for\x18\x0e \x01(\tR\rxForwardedFor\x12,\n" +
	"\x12async_operation_id\x18\x0f \x01(\tR\x10asyncOperationId\"a\n" +
	"\tPrincipal\x12\x12\n" +
	"\x04type\x18\x01 \x01(\tR\x04type\x12\x0e\n" +
	"\x02id\x18\x02 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\x12\x1c\n" +
	"\n" +
	"api_key_id\x18\x04 \x01(\tR\bapiKeyIdB\xac\x01\n" +
	"!io.temporal.api.cloud.auditlog.v1B\fMessageProtoP\x01Z-go.temporal.io/api/cloud/auditlog/v1;auditlog\xaa\x02 Temporalio.Api.Cloud.AuditLog.V1\xea\x02$Temporalio::Api::Cloud::AuditLog::V1b\x06proto3"

var (
	file_temporal_api_cloud_auditlog_v1_message_proto_rawDescOnce sync.Once
	file_temporal_api_cloud_auditlog_v1_message_proto_rawDescData []byte
)

func file_temporal_api_cloud_auditlog_v1_message_proto_rawDescGZIP() []byte {
	file_temporal_api_cloud_auditlog_v1_message_proto_rawDescOnce.Do(func() {
		file_temporal_api_cloud_auditlog_v1_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_temporal_api_cloud_auditlog_v1_message_proto_rawDesc), len(file_temporal_api_cloud_auditlog_v1_message_proto_rawDesc)))
	})
	return file_temporal_api_cloud_auditlog_v1_message_proto_rawDescData
}

var file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_temporal_api_cloud_auditlog_v1_message_proto_goTypes = []any{
	(*LogRecord)(nil),             // 0: temporal.api.cloud.auditlog.v1.LogRecord
	(*Principal)(nil),             // 1: temporal.api.cloud.auditlog.v1.Principal
	(*timestamppb.Timestamp)(nil), // 2: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 3: google.protobuf.Struct
}
var file_temporal_api_cloud_auditlog_v1_message_proto_depIdxs = []int32{
	2, // 0: temporal.api.cloud.auditlog.v1.LogRecord.emit_time:type_name -> google.protobuf.Timestamp
	1, // 1: temporal.api.cloud.auditlog.v1.LogRecord.principal:type_name -> temporal.api.cloud.auditlog.v1.Principal
	3, // 2: temporal.api.cloud.auditlog.v1.LogRecord.raw_details:type_name -> google.protobuf.Struct
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_temporal_api_cloud_auditlog_v1_message_proto_init() }
func file_temporal_api_cloud_auditlog_v1_message_proto_init() {
	if File_temporal_api_cloud_auditlog_v1_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_temporal_api_cloud_auditlog_v1_message_proto_rawDesc), len(file_temporal_api_cloud_auditlog_v1_message_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_temporal_api_cloud_auditlog_v1_message_proto_goTypes,
		DependencyIndexes: file_temporal_api_cloud_auditlog_v1_message_proto_depIdxs,
		MessageInfos:      file_temporal_api_cloud_auditlog_v1_message_proto_msgTypes,
	}.Build()
	File_temporal_api_cloud_auditlog_v1_message_proto = out.File
	file_temporal_api_cloud_auditlog_v1_message_proto_goTypes = nil
	file_temporal_api_cloud_auditlog_v1_message_proto_depIdxs = nil
}
